export const TaskListingObj ={
    dependencyPopup : {
        popUpMain: 'tsks-lstng-dpndncy-ppup',
        dpndncySctn: 'tsks-lstng-dpndncy-sctn',
        inptSctn: 'tsk-lstng-dpndncy-inpt-icn',
        srchinpt: 'tsk-lstng-dpndy-srch-inpt',
        srchIcn: 'srch-icn',
        dpndcyLst: 'task-lstng-slct-tsk-dpdncy-lst',
        hdrTxt:'tsk-lstng-dpdncy-hdr-txt',
        cstmScrl: 'tsk-lstng-dpndncy-cstm-scrl',
        ulList: 'tsk-lstng-dpndcy-lst',
        menu: 'tasks-lstng-dpndncy-menu',
        lstName: 'tsk-lstng-dpndncy-lst-name',
        cgckBx : 'tsk-lstng-dpndncy-chck-bx',
        lstChck: 'tsk-lstng-chckbx',
        lstNme : 'dpndncy-lst-nme',
      },
      dependencyTxt : {
        placeholder : 'SELECT TASK DEPENDENCY'
    },

    colorPickerStls : {
        popupOne: 'tsks-lstng-clr-pckr-ppup-fr-one',
          clrSctn: 'tsks-lstng-clr-sctn',
          clrHdrTxt: 'tsk-lstng-clr-pckr-hdr-txt',
          clrPckrLst : 'task-lstng-clr-pckr-lst',
          cstScrl : 'custom-scroll',
          popupLst: 'tsk-lstng-clr-pckr-popup-lst',
          pckrMenu: 'tasks-lstng-clr-pckr-menu d-flex justify-space-between',
          lstname: 'tsk-lstng-lst-name d-flex align-items-center',
          chckBox: 'tsk-lstng-chck-bx',
          asgnChkBx: 'tsk-lstng-asgn-chckbx',
          listname: 'lst-nme',
          menuPrf: 'menu-profile',
          brk: 'tsk-lstng-brk',
          add: 'tsk-lstng-inpt-add',
          srchInpt: 'tsk-lstng-clr-pckr-srch-inpt',
          addIcn: 'add-icn',
          slctSctn: 'tsk-lstng-clrs-slct-sctn',
          tray: 'tgs-clr-pckr-tray',
          picker: 'tgs-crcl-clr-pckr',
          lstngClr: 'tsk-lstng-clrs',
          icnTxt: 'prvcy-icn-txt',
          prcyIcn: 'prvcy-lck',
          mkTxt: 'mke-prvt-txt ',
          clrSctn: 'tsk-lstng-prvcy-chckbx'
      },
    
      AssignText : {
          placeholder : 'ASSIGN/TRANSFER'
      },

      AssignStyles: {
          popMain : 'tsks-lstng-assgn-ppup-fr-one',
          asgnDtls : 'tsks-lstng-assgn-dtails',
          hdreSctn : 'asgn-hdr-sctn',
          toglr : 'sidbr-cls-icn',
          hdrTxt : 'tsk-lstng-assgn-dtls-hdr-txt',
          srchBr : 'tsk-lstng-assgn-srchbr',
          srchFild : 'sidebar-search-field',
          srchIcnSctn : 'task-lstng-srch-icn-sctn',
          icnSrch : 'task-lstng-srch-icn',
          prfl : 'task-lstng-asgn-prfle',
          scrl : 'custom-scroll',
          prflLst : 'tsk-lstng-assgn-popup-prfl-lst',
          asgnMenu : 'tasks-lstng-assgn-menu d-flex justify-space-between',
          prflName : 'tsk-lst-prfl-name d-flex align-items-center',
          MnuPrfl : 'menu-profile',
          prfllbl : 'profile-name',
          chckBx : 'tsk-lstng-chck-bx',
          asgnChckBx : 'tsk-lstng-asgn-chckbx',
      },

      MoreAssignStyles: {
        popMain : 'tsk-lst-popup-assgn-frm-mre',
        asgnDtls : 'tsks-lstng-assgn-dtails',
        hdreSctn : 'asgn-hdr-sctn',
        toglr : 'sidbr-cls-icn',
        hdrTxt : 'tsk-lstng-assgn-dtls-hdr-txt',
        srchBr : 'tsk-lstng-assgn-srchbr',
        srchFild : 'sidebar-search-field',
        srchIcnSctn : 'task-lstng-srch-icn-sctn',
        icnSrch : 'task-lstng-srch-icn',
        prfl : 'task-lstng-asgn-prfle',
        scrl : 'tsk-lstng-assgn-trnsfr-pple-scroll',
        prflLst : 'tsk-lstng-assgn-popup-prfl-lst',
        asgnMenu : 'tasks-list-icon-people-check ',
        prflName : 'tsk-lst-prfl-name d-flex align-items-center',
        MnuPrfl : 'menu-profile',
        prfllbl : 'profile-name',
        chckBx : 'tsk-lstng-chck-bx',
        asgnChckBx : 'tsk-lstng-asgn-chckbx',
    }

    
} 
